REGRESSION(299013@main): [GCC] RemoteGraphicsContextGL reports the free-nonheap-object compiler warning https://bugs.webkit.org/show_bug.cgi?id=298080
Unreviewed build fix for GTK and WPE debug builds.
After <https://commits.webkit.org/299013@main> changed
RemoteGraphicsContextGL class to inherit
StreamServerConnection::Client class, GCC reported a warning for GTK
and WPE debug builds.

> Source/WebKit/GPUProcess/graphics/RemoteGraphicsContextGL.cpp:106:1:
>   error: ‘static void IPC::StreamServerConnectionClient::operator delete(IPC::StreamServerConnectionClient*, std::destroying_delete_t, size_t)’
>   called on pointer ‘<unknown>’ with nonzero offset 8 [-Werror=free-nonheap-object]

This is a GCC bug. <https://gcc.gnu.org/bugzilla/show_bug.cgi?id=121717>
Ignore the warning.

* Source/WebKit/GPUProcess/graphics/RemoteGraphicsContextGL.cpp:

Canonical link: https://commits.webkit.org/299309@main