[GTK] [2.49.90] Fails to build in s390x: undefined reference to `WebCore::Style::BuilderState::setFontDescriptionFontSize(float)' https://bugs.webkit.org/show_bug.cgi?id=298308
Unreviewed build fix.

This just includes a missing header file.

Canonical link: https://commits.webkit.org/300388@main