[watchOS debug] Build broken because of undefined symbol WebKit::WebPage::drawPDFDocument https://bugs.webkit.org/show_bug.cgi?id=293210 rdar://151573329
Unreviewed build fix.

The !HAVE_PDFKIT configuration does not provide a definition for
WebPage::drawPDFDocument, and as such fails to link. This can be seen in
the debug watchOS build.

```
Undefined symbols for architecture arm64e:
  "WebKit::WebPage::drawPDFDocument(CGContext*, PDFDocument*, WebKit::PrintInfo const&, WebCore::IntRect const&)", referenced from:
      WebKit::WebPage::drawRectToImage(WTF::ObjectIdentifierGeneric<WebCore::FrameIdentifierType, WTF::ObjectIdentifierMainThreadAccessTraits<unsigned long long>, unsigned long long>, WebKit::PrintInfo const&, WebCore::IntRect const&, WebCore::IntSize const&, WTF::CompletionHandler<void (std::__1::optional<WebCore::ShareableBitmapHandle>&&)>&&) in UnifiedSource137.o
ld: symbol(s) not found for architecture arm64e
```

This patch provides a placeholder implementation for drawPDFDocument in
the relevant configuration.

* Source/WebKit/WebProcess/WebPage/Cocoa/WebPageCocoa.mm:
(WebKit::WebPage::drawPDFDocument):

Canonical link: https://commits.webkit.org/295082@main