TestWebKitAPIApp fails to build with error: TestWebKitAPIResources.bundle: No such file or directory https://bugs.webkit.org/show_bug.cgi?id=288138
Reviewed by Abrar Rahman Protyasha and Elliott Williams.

When building a scheme that enables "Find Implicit Dependencies" and includes TestWebKitAPIApp,
the build fails with errors such as:

    error: /.../WebKitBuild/Debug-iphoneos/TestWebKitAPIResources.bundle: No such file or directory
    (in target 'TestWebKitAPIApp' from project 'TestWebKitAPI')

TestWebKitAPIResources.bundle was included in TestWebKitAPIApp's "Copy Bundle Resources" build
phase, but it turns out that this type of build phase does not establish implicit dependencies.
Replaced it with a "Copy Files" build phase, which does establish implicit dependencies.

* Tools/TestWebKitAPI/TestWebKitAPI.xcodeproj/project.pbxproj:

Canonical link: https://commits.webkit.org/290769@main