[watchOS] Fix the open source watchOS 11.4 build https://bugs.webkit.org/show_bug.cgi?id=293052
Reviewed by Abrar Rahman Protyasha.

Fix the open source watchOS 11.4 build, which current fails in:

```
In file included from […]/WebKitBuild/Release-watchsimulator/DerivedSources/WebKit/unified-sources/UnifiedSource59-mm.mm:7:
[…]/Source/WebKit/UIProcess/ios/forms/WKFocusedFormControlView.mm:71:17: error: class 'WKFocusedFormControlView' does not conform to protocol 'UITextInputDelegate' [-Werror,-Wprotocol]
   71 | @implementation WKFocusedFormControlView {
[…]/Source/WebKit/UIProcess/ios/forms/WKFocusedFormControlView.mm:71:17: note: add stubs for missing protocol requirements
   71 | @implementation WKFocusedFormControlView {
1 error generated.
```

...due to the introduction of `-conversationContext:didChange:` to the public iOS SDK. This is
normally marked unavailable on watchOS in the internal SDK, but open source watchOS builds use
headers symlinked from the iOS SDK, which don't have these (un)availability declarations.

* Source/WebKit/UIProcess/ios/WKContentViewInteraction.mm:
(-[WKContentView addFocusedFormControlOverlay]):

Static cast to `id<UITextInputDelegate>` here when setting the input delegate. I suspect that we can
remove this entirely too (since the focused form control view is effectively just a helper object
used to store text suggestions), but we'll leave that for a future patch.

* Source/WebKit/UIProcess/ios/forms/WKFocusedFormControlView.h:
* Source/WebKit/UIProcess/ios/forms/WKFocusedFormControlView.mm:
(-[WKFocusedFormControlView handleWebViewCredentialsSaveForWebsiteURL:user:password:passwordIsAutoGenerated:]): Deleted.

Delete a method stub that was only added here to avoid a build failure. This is no longer necessary,
now that `WKFocusedFormControlView` is no longer a `UITextInputDelegate`. I'm keeping the other
protocol methods intact for now for binary compatibility with first-party system frameworks, though
those could potentially be removed as well.

Canonical link: https://commits.webkit.org/294977@main