Register about scheme handler with other scheme handlers https://bugs.webkit.org/show_bug.cgi?id=290653 rdar://148125287
Reviewed by Basuke Suzuki.

Before this change, I often see this message printed:
ERROR: Unhandled web process message 'WebPage_RegisterURLSchemeHandler' (destination: 10 pid: 97447)
After this change, it goes away.  Reproduced reliably on macOS when running the API test
TestWebKitAPI.WKWebView.LocalStorageDifferentPageGroupSameProcess

While I was at it, I made the member a const Ref so we don't need to protect it as much.

* Source/WebKit/UIProcess/API/Cocoa/WKWebView.mm:
(-[WKWebView _initializeWithConfiguration:]):
* Source/WebKit/UIProcess/WebPageProxy.cpp:
(WebKit::m_pageForTesting):

Canonical link: https://commits.webkit.org/292882@main