REGRESSION(300548@main): RenderTableSection.cpp has to include "StylePrimitiveNumericTypes+Evaluation.h" https://bugs.webkit.org/show_bug.cgi?id=299658
Unreviewed non-unified build fix.

> StyleValueTypes.h:706:5: error: non-void function does not return a value [-Werror,-Wreturn-type]

* Source/WebCore/rendering/RenderTableSection.cpp:

Canonical link: https://commits.webkit.org/300652@main