[GStreamer][WebRTC] Fix build error in GStreamerWebRTCCommon.cpp https://bugs.webkit.org/show_bug.cgi?id=293892
Unreviewed build fix.

Fix build error in GStreamerWebRTCCommon.cpp due to a missing
definition:

  ../mediastream/gstreamer/GStreamerWebRTCCommon.cpp:22:19:
  error: expected constructor, destructor, or type conversion before '(' token
    GST_DEBUG_CATEGORY(webkit_webrtc_common_debug);
  ../mediastream/gstreamer/GStreamerWebRTCCommon.cpp:31:33:
  error: 'webkit_webrtc_common_debug' was not declared in this scope
     GST_DEBUG_CATEGORY_INIT(webkit_webrtc_common_debug,
                             "webkitwebrtccommon", 0,
                             "WebKit WebRTC Common");

Related to https://bugs.webkit.org/show_bug.cgi?id=293735

* Source/WebCore/platform/mediastream/gstreamer/GStreamerWebRTCCommon.cpp:

Canonical link: https://commits.webkit.org/295674@main