REGRESSION(315639@main): Broke macOS 27 builds with down-level deployment target (unguarded-availability-new) https://bugs.webkit.org/show_bug.cgi?id=317711 rdar://180467126
Unreviewed build fix.

This patch addresses the following build failure:

```
Source/WebKit/UIProcess/API/Cocoa/WKWebView.h:750:30: error: 'NSRefreshController' is only available on macOS 27.0 or newer [-Werror,-Wunguarded-availability-new]
```

It is possible to hit this issue when targeting downlevel macOS versions
while building against a macOS 27 SDK. Since NSRefreshController is a
type new to macOS 27, we need to guard the API declaration behind the
appropriate macOS minimum version guard.

* Source/WebKit/UIProcess/API/Cocoa/WKWebView.h:

Canonical link: https://commits.webkit.org/315728@main