REGRESSION(299308@main): Internal TestWebKitAPI builds are broken https://bugs.webkit.org/show_bug.cgi?id=298089 rdar://159433840
Unreviewed build fix.

TestWebKitAPI/Tests/WTF/bmalloc/IsoHeap.cpp does not build against
internal SDKs. In these configurations, `OS_UNFAIR_LOCK_INLINE` should
be set to 1.

```
/Build/Debug/usr/local/include/bmalloc/pas_lock.h:125:2: error: "OS_UNFAIR_LOCK_INLINE needs to be enabled."
  125 | #error "OS_UNFAIR_LOCK_INLINE needs to be enabled."
```

The caused-by removes `WK_OS_UNFAIR_LOCK_INLINE_CFLAGS` from the common
base config. This is a definition (still) depended on by other targets,
such as TestWebKitAPI.

In this build fix patch, we restore `WK_OS_UNFAIR_LOCK_INLINE_CFLAGS`
and use it in the `WK_GCC_PREPROCESSOR_DEFINITIONS` definition. This
lets targets continue using only `WK_OS_UNFAIR_LOCK_INLINE_CFLAGS`
without the general GCC preprocessor definitions set, such as TWKAPI.

* Configurations/CommonBase.xcconfig:

Canonical link: https://commits.webkit.org/299317@main