[JSC] Build is broken on macOS mach-O https://bugs.webkit.org/show_bug.cgi?id=293383 rdar://151779679
Reviewed by Mark Lam.

We are getting an error.

```
error: <inline asm>:64:1: non-private labels cannot appear between .cfi_startproc / .cfi_endproc pairs
_vmEntryToJavaScript:
^
```

This is because Mach-O does not support nested cfi_startproc /
cfi_endproc[1] because Mach-O supports subsections_via_symbols.
Right now, we just disable them on Darwin to fix the build breakage.

We also disable GdbJIT binary dump. It should be controlled via options.
And under macOS, it does not work.

[1]: https://github.com/llvm/llvm-project/issues/72802

* Source/JavaScriptCore/llint/LowLevelInterpreter.asm:
* Source/JavaScriptCore/llint/LowLevelInterpreter.cpp:

Canonical link: https://commits.webkit.org/295234@main