REGRESSION(314348@main): Broke WebCore module verification in some visionOS configurations https://bugs.webkit.org/show_bug.cgi?id=316077 rdar://178504409
Unreviewed build fix.

We convert the WebCore private header include to be angle-bracketed,
rather than double-quoted. This addresses the following module
verification error:

```
XRCompositionLayerPose.h:30:10: error: double-quoted include "PlatformXR.h" in framework header, expected angle-bracketed instead [-Werror,-Wquoted-include-in-framework-header]
   30 | #include "PlatformXR.h"
```

* Source/WebCore/Modules/webxr/XRCompositionLayerPose.h:

Canonical link: https://commits.webkit.org/314351@main