REGRESSION(315027@main): [GTK] skia/src/gpu/ganesh/GrSurfaceProxy.cpp:484: fatal error: "assertf(surface->backendFormat() == fFormat): OpenGL-BGRA8 != OpenGL-RGBA8" https://bugs.webkit.org/show_bug.cgi?id=317120
Reviewed by Carlos Garcia Campos.

Pass the color type from the image to the backend format in createPromiseImageIfNeeded()
instead of assuming RGBA8888.

Do the same in SkiaGPUAtlas::atlasImageForCurrentThread(), where the promise image also
assumed RGBA8888 while the atlas texture uses a BGRA8888 layout, just like the non-promise
path that borrows the texture already does.

Covered by existing tests.

* Source/WebCore/platform/graphics/skia/SkiaGPUAtlas.cpp:
(WebCore::SkiaGPUAtlas::atlasImageForCurrentThread const):
* Source/WebCore/platform/graphics/skia/SkiaUtilities.cpp:
(WebCore::SkiaUtilities::createPromiseImageIfNeeded):

Canonical link: https://commits.webkit.org/315218@main