REGRESSION(315639@main): Broke internal macOS builds (invalid preprocessing token in refreshController API declaration) https://bugs.webkit.org/show_bug.cgi?id=317647 rdar://180396220
Unreviewed build fix.

WK_API_AVAILABLE(...) needs to be followed by the platform identifier
(macos, ios, visionos) as well as a platform version where said API is
introduced. As such, WK_API_AVAILABLE(WK_MAC_TBA) is not a valid
annotation. This patch fixes the issue by prefixing with `macos(...)`,
alleviating this build failure:

```
WKWebView.h:748:69: error: pasting formed '__API_AVAILABLE_PLATFORM_26.0', an invalid preprocessing token
  748 | @property (strong, nullable) NSRefreshController *refreshController API_AVAILABLE(26.0);
```

* Source/WebKit/UIProcess/API/Cocoa/WKWebView.h:

Canonical link: https://commits.webkit.org/315671@main