[libpas] Fix the libpas tests build https://bugs.webkit.org/show_bug.cgi?id=293960 rdar://152507524
Reviewed by Yijia Huang.

* Source/bmalloc/libpas/libpas.xcodeproj/project.pbxproj:

pas_thread.{c,h} was added in 295497@main so add it to the
xcode project so that the tests can be built on darwin.

* Source/bmalloc/libpas/src/libpas/pas_segregated_shared_view.h:
(pas_segregated_shared_view_compute_minimum_size_for_bump_with_aligned_padding):

This function was added in 293476@main. The compiler complains about the
implicit conversion when building the tests but not when building the product.
Add the cast to silence the warning  (promoted to error), like we do in other places.

OpenSource/Source/bmalloc/libpas/src/libpas/pas_segregated_shared_view.h:137:9: error:
      implicit conversion loses integer precision: 'uintptr_t' (aka 'unsigned long') to 'unsigned int'
      [-Werror,-Wshorten-64-to-32]
  136 |     return pas_round_up_to_power_of_2(allocation_size, trailing_padding_alignment)
      |     ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  137 |         + trailing_padding_size;
      |         ^~~~~~~~~~~~~~~~~~~~~~~

Canonical link: https://commits.webkit.org/295762@main