REGRESSION(297392@main): Tentative build fix for Ubuntu 2204 https://bugs.webkit.org/show_bug.cgi?id=296047
Reviewed by Gerald Squelart.

This should fix

  error: ‘static bool WebCore::MediaSampleReorderQueueComparator::operator()
  (const WTF::Ref<const WebCore::MediaSample>&,
  const WTF::Ref<const WebCore::MediaSample>&)’ must be a non-static member function

* Source/WebCore/platform/graphics/MediaReorderQueue.h:
(WebCore::MediaSampleReorderQueueComparator::operator() const):
(WebCore::MediaSampleReorderQueueComparator::operator()):

Canonical link: https://commits.webkit.org/297545@main