WebFullScreenManager{Proxy,Manager}: add missing includes
https://bugs.webkit.org/show_bug.cgi?id=290261

Reviewed by Adrian Perez de Castro.

/home/thomas/br-test-pkg/bootlin-armv7-glibc/build/webkitgtk-2.48.0/Source/WebKit/WebProcess/FullScreen/WebFullScreenManager.h:69:140: error: ‘ExceptionOr’ is not a member of ‘WebCore’
   69 |     void enterFullScreenForElement(WebCore::Element&, WebCore::HTMLMediaElementEnums::VideoFullscreenMode, CompletionHandler<void(WebCore::ExceptionOr<void>)>&&, CompletionHandler<bool(bool)>&&);
      |                                                                                                                                            ^~~~~~~~~~~

/home/thomas/br-test-pkg/bootlin-armv7-glibc/build/webkitgtk-2.48.0/Source/WebKit/WebProcess/FullScreen/WebFullScreenManager.h:79:42: error: ‘WebCore::FrameIdentifier’ has not been declared
   79 |     void enterFullScreenForOwnerElements(WebCore::FrameIdentifier, CompletionHandler<void()>&&);
      |                                          ^~~~~~~

/home/thomas/br-test-pkg/bootlin-armv7-glibc/build/webkitgtk-2.48.0/Source/WebKit/UIProcess/WebFullScreenManagerProxy.h:104:58: error: ‘WebCore::FrameIdentifier’ has not been declared
  104 |     void enterFullScreenForOwnerElementsInOtherProcesses(WebCore::FrameIdentifier, CompletionHandler<void()>&&);
      |                                                          ^~~~~~~

Signed-off-by: Thomas Devoogdt <thomas@devoogdt.com>
Canonical link: https://commits.webkit.org/292681@main