Linking failure in RemoteScrollingCoordinatorProxy::hasFixedOrSticky() under certain configurations https://bugs.webkit.org/show_bug.cgi?id=297447 rdar://158381182
Unreviewed build fix.

In some build configurations, the build is broken because the linker
cannot find WebCore::ScrollingTree::hasFixedOrSticky():

```
Undefined symbols for architecture arm64e:
  "__ZNK7WebCore13ScrollingTree16hasFixedOrStickyEv", referenced from:
  ¦ ¦ __ZNK6WebKit31RemoteScrollingCoordinatorProxy16hasFixedOrStickyEv in UnifiedSource103.o
ld: symbol(s) not found for architecture arm64e
```

... expectedly so, because the `ScrollingTree::hasFixedOrSticky()`
declaration has hidden visibility. This patch fixes the issue by
applying WEBCORE_EXPORT on the declaration.

* Source/WebCore/page/scrolling/ScrollingTree.h:

Canonical link: https://commits.webkit.org/298759@main