REGRESSION(299600@main): Broke production builds https://bugs.webkit.org/show_bug.cgi?id=298437 rdar://159921175
Unreviewed build fix.

Production builds broken with 299600@main because the availability
annotations were missing platform identifiers `macos`/`ios` around the
version placeholders, producing build errors like this:

```
/System/Library/Frameworks/WebKit.framework/PrivateHeaders/WKPreferencesPrivate.h:125:184: error: expected ','
123 | @property (nonatomic, setter=_setICECandidateFilteringEnabled:) BOOL _iceCandidateFilteringEnabled API_AVAILABLE(macos(10.13.4), ios(11.3));
124 | @property (nonatomic, setter=_setInactiveMediaCaptureStreamRepromptIntervalInMinutes:) double _inactiveMediaCaptureStreamRepromptIntervalInMinutes API_AVAILABLE(macos(10.13.4), ios(11.3));
125 | @property (nonatomic, setter=_setInactiveMediaCaptureStreamRepromptWithoutUserGestureIntervalInMinutes:) double _inactiveMediaCaptureStreamRepromptWithoutUserGestureIntervalInMinutes API_AVAILABLE(NA, NA);
    |                                                                                                                                                                                        `- error: expected ','
126 | @property (nonatomic, setter=_setInterruptAudioOnPageVisibilityChangeEnabled:) BOOL _interruptAudioOnPageVisibilityChangeEnabled API_AVAILABLE(macos(10.15), ios(13.0));
127 |
```

* Source/WebKit/UIProcess/API/Cocoa/WKPreferencesPrivate.h:

Canonical link: https://commits.webkit.org/299609@main