REGRESSION(299937@main): Fix GTK3 builds https://bugs.webkit.org/show_bug.cgi?id=298385
Unreviewed build fix for GTK3 build.

> Source/WebKit/UIProcess/API/glib/WebKitNetworkSession.cpp:21:10: fatal error: WebKitNetworkSession.h: No such file or directory
>    21 | #include "WebKitNetworkSession.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~

Moved the #if before #include "WebKitNetworkSession.h".

* Source/WebKit/UIProcess/API/glib/WebKitNetworkSession.cpp:

Canonical link: https://commits.webkit.org/299938@main