[SwiftBrowser] Internal iOS builds are broken https://bugs.webkit.org/show_bug.cgi?id=299404 rdar://161204348
Unreviewed build fix.

In this patch, we address this build failure:

```
SwiftCompile normal arm64 /OpenSource/Tools/SwiftBrowser/Source/Views/BrowserView.swift (in target 'SwiftBrowser' from project 'SwiftBrowser')
    cd /OpenSource/Tools/SwiftBrowser

/OpenSource/Tools/SwiftBrowser/Source/Views/BrowserView.swift:48:17: error: for-in loop uses unsafe constructs but is not marked with 'unsafe'
                for await _ in NotificationCenter.default.messages(of: UserDefaults.self, for: .didChange) {
                ^
                          unsafe
/OpenSource/Tools/SwiftBrowser/Source/Views/BrowserView.swift:48:17: note: reference to nonisolated(unsafe) var '$generator' is unsafe in concurrently-executing code
                for await _ in NotificationCenter.default.messages(of: UserDefaults.self, for: .didChange) {
```

... which is not actually an unsafe construct, but we have to work
around rdar://154775389 for now, check 300022@main for precedence.

* Tools/SwiftBrowser/Source/Views/BrowserView.swift:
(BrowserView.body):

Canonical link: https://commits.webkit.org/300434@main