[JSC] Move some inline functions from AirTmpWidth.h to AirTmpWidthInlines.h https://bugs.webkit.org/show_bug.cgi?id=288181
Reviewed by Yusuke Suzuki.

Non-unified source build couldn't compile:

> JavaScriptCore/b3/air/AirTmpWidth.h(109,20): error: inline function 'JSC::B3::Air::TmpWidth::widths' is not defined
> JavaScriptCore/b3/air/AirTmpWidth.h(64,28): note: used here
>    64 |         Widths tmpWidths = widths(tmp);
>       |                            ^

An inline function `requiredWidth` was using an inline function
`widths` which was defined in AirTmpWidthInlines.h.

Inline functions which use inline functions in *Inlines.h should move
into *Inlines.h.

* Source/JavaScriptCore/b3/air/AirAllocateRegistersByGreedy.cpp:
* Source/JavaScriptCore/b3/air/AirTmpWidth.h:
(JSC::B3::Air::TmpWidth::width const): Deleted.
(JSC::B3::Air::TmpWidth::requiredWidth): Deleted.
(JSC::B3::Air::TmpWidth::defWidth const): Deleted.
(JSC::B3::Air::TmpWidth::useWidth const): Deleted.
(JSC::B3::Air::TmpWidth::widths const): Deleted.
(JSC::B3::Air::TmpWidth::addWidths): Deleted.
* Source/JavaScriptCore/b3/air/AirTmpWidthInlines.h:
(JSC::B3::Air::TmpWidth::widths const):
(JSC::B3::Air::TmpWidth::width const):
(JSC::B3::Air::TmpWidth::addWidths):
(JSC::B3::Air::TmpWidth::requiredWidth):
(JSC::B3::Air::TmpWidth::defWidth const):
(JSC::B3::Air::TmpWidth::useWidth const):

Canonical link: https://commits.webkit.org/290830@main